language: node_js
node_js:
  - "4.4.5"

before_script:
  - npm install

script:
  - npm test

after_success:
  - ./node_modules/.bin/lcov-result-merger 'coverage/angular-*/**/lcov.info' coverage/combined-lcov.info
  - ./node_modules/.bin/grunt upload-combined-coverage
